from pystache import Renderer
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import base64
from io import BytesIO
from PIL import Image


def screenshot(table):
    options = Options()
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--headless")
    options.add_argument("window-size=1500,2000")
    chrome = webdriver.Chrome("./chromedriver", chrome_options=options)

    html_bs64 = base64.b64encode(table.encode("utf-8")).decode()
    chrome.get("data:text/html;base64," + html_bs64)
    e = chrome.find_element_by_class_name("main")
    left = e.location["x"]
    top = e.location["y"]
    right = e.location["x"] + e.size["width"]
    bottom = e.location["y"] + e.size["height"]
    png = chrome.get_screenshot_as_png()
    chrome.quit()
    im = Image.open(BytesIO(png))
    im = im.crop((left, top, right, bottom))
    # im.save("screenshot.png")
    return im


recent_data = {
    "avg_stats": {
        "battles": 24,
        "winrate": {"value": 75.0, "color": "#a00dbc"},
        "pr": {"value": 2571, "color": "#a00dbc"},
        "dmg": {"value": 76192, "color": "#d042f3"},
        "frags": {"value": 1.08, "color": "#44b300"},
        "planes": {"value": 9.29, "color": "#d042f3"},
    },
    "all_ships": [
        {
            "name": "Groningen",
            "tier": "IX",
            "tier_num": "9",
            "battles": 13,
            "winrate": {"value": "76.92", "color": "#a00dbc"},
            "pr": {"value": "2616", "color": "#a00dbc"},
            "dmg": {"value": 79892, "color": "#D042F3"},
            "frags": {"value": "1.46", "color": "#d042f3"},
            "planes": {"value": "13.08", "color": "#d042f3"},
        },
        {
            "name": "Kiev",
            "tier": "VIII",
            "tier_num": "8",
            "battles": 11,
            "winrate": {"value": "72.73", "color": "#a00dbc"},
            "pr": {"value": "2517", "color": "#a00dbc"},
            "dmg": {"value": 71820, "color": "#D042F3"},
            "frags": {"value": "0.64", "color": "#fe7903"},
            "planes": {"value": "4.82", "color": "#02c9b3"},
        },
    ],
    "day": 7,
    "clan": {"name": "[PANTS]", "color": "#cda4ff"},
    "user": {"uid": 2025455227, "nickname": "B2U"},
}
single_ship_data = {
    "ship": {
        "name": "Groningen",
        "tier": "IX",
        "battles": 46,
        "pr": {"value": 2569, "color": "#a00dbc"},
        "winrate": {"value": 76.09, "color": "#a00dbc"},
        "dmg": {"value": 78852, "color": "#FFF"},
        "frags": {"value": 1.43, "color": "#02c9b3"},
        "planes": {"value": 10.5, "color": "#d042f3"},
    },
    "clan": {"name": "[PANTS]", "color": "#cda4ff"},
    "user": {"uid": 2025455227, "nickname": "B2U"},
}
overall_data = {
    "div": {
        "pvp": {
            "battles": 1460,
            "winrate": {"value": 73.49, "color": "#a00dbc"},
            "dmg": {"value": 77151, "color": "#d042f3"},
            "frags": {"value": 1.44, "color": "#02c9b3"},
            "planes": {"value": 5.12, "color": "#02c9b3"},
            "pr": {"value": 2397, "color": "#d042f3"},
        },
        "pvp_solo": {
            "battles": 447,
            "winrate": {"value": 61.3, "color": "#d042f3"},
            "dmg": {"value": 80517, "color": "#d042f3"},
            "frags": {"value": 1.9, "color": "#d042f3"},
            "planes": {"value": 3.96, "color": "#02c9b3"},
            "pr": {"value": 2897, "color": "#a00dbc"},
        },
        "pvp_div2": {
            "battles": 221,
            "winrate": {"value": 72.4, "color": "#a00dbc"},
            "dmg": {"value": 69730, "color": "#d042f3"},
            "frags": {"value": 1.33, "color": "#02c9b3"},
            "planes": {"value": 3.52, "color": "#44b300"},
            "pr": {"value": 2316, "color": "#d042f3"},
        },
        "pvp_div3": {
            "battles": 792,
            "winrate": {"value": 80.68, "color": "#a00dbc"},
            "dmg": {"value": 77323, "color": "#d042f3"},
            "frags": {"value": 1.21, "color": "#02c9b3"},
            "planes": {"value": 6.23, "color": "#d042f3"},
            "pr": {"value": 2185, "color": "#d042f3"},
        },
    },
    "tier": {
        "1": {
            "battles": 0,
            "winrate": {"value": 0, "color": "#fe0e00"},
            "dmg": {"value": 0, "color": "#fe0e00"},
            "frags": {"value": 0, "color": "#fe0e00"},
            "planes": {"value": 0, "color": "#fe0e00"},
            "pr": {"value": 0, "color": "#fe0e00"},
            "roman": "I",
        },
        "2": {
            "battles": 82,
            "winrate": {"value": 85.37, "color": "#a00dbc"},
            "dmg": {"value": 55866, "color": "#d042f3"},
            "frags": {"value": 3.94, "color": "#d042f3"},
            "planes": {"value": 0.0, "color": "#fe0e00"},
            "pr": {"value": 9013, "color": "#a00dbc"},
            "roman": "II",
        },
        "3": {
            "battles": 35,
            "winrate": {"value": 74.29, "color": "#a00dbc"},
            "dmg": {"value": 46629, "color": "#02c9b3"},
            "frags": {"value": 2.2, "color": "#d042f3"},
            "planes": {"value": 0.06, "color": "#fe0e00"},
            "pr": {"value": 3754, "color": "#a00dbc"},
            "roman": "III",
        },
        "4": {
            "battles": 64,
            "winrate": {"value": 79.69, "color": "#a00dbc"},
            "dmg": {"value": 54045, "color": "#d042f3"},
            "frags": {"value": 1.98, "color": "#d042f3"},
            "planes": {"value": 3.55, "color": "#44b300"},
            "pr": {"value": 3250, "color": "#a00dbc"},
            "roman": "IV",
        },
        "5": {
            "battles": 68,
            "winrate": {"value": 80.88, "color": "#a00dbc"},
            "dmg": {"value": 50942, "color": "#d042f3"},
            "frags": {"value": 1.41, "color": "#02c9b3"},
            "planes": {"value": 2.97, "color": "#44b300"},
            "pr": {"value": 3184, "color": "#a00dbc"},
            "roman": "V",
        },
        "6": {
            "battles": 153,
            "winrate": {"value": 69.93, "color": "#a00dbc"},
            "dmg": {"value": 63240, "color": "#d042f3"},
            "frags": {"value": 1.35, "color": "#02c9b3"},
            "planes": {"value": 4.63, "color": "#02c9b3"},
            "pr": {"value": 2629, "color": "#a00dbc"},
            "roman": "VI",
        },
        "7": {
            "battles": 50,
            "winrate": {"value": 66.0, "color": "#a00dbc"},
            "dmg": {"value": 57485, "color": "#d042f3"},
            "frags": {"value": 1.3, "color": "#02c9b3"},
            "planes": {"value": 2.18, "color": "#44b300"},
            "pr": {"value": 2629, "color": "#a00dbc"},
            "roman": "VII",
        },
        "8": {
            "battles": 323,
            "winrate": {"value": 72.76, "color": "#a00dbc"},
            "dmg": {"value": 76128, "color": "#d042f3"},
            "frags": {"value": 1.15, "color": "#44b300"},
            "planes": {"value": 6.94, "color": "#d042f3"},
            "pr": {"value": 2131, "color": "#d042f3"},
            "roman": "VIII",
        },
        "9": {
            "battles": 481,
            "winrate": {"value": 72.35, "color": "#a00dbc"},
            "dmg": {"value": 82727, "color": "#d042f3"},
            "frags": {"value": 1.26, "color": "#02c9b3"},
            "planes": {"value": 5.41, "color": "#02c9b3"},
            "pr": {"value": 2086, "color": "#02c9b3"},
            "roman": "IX",
        },
        "10": {
            "battles": 204,
            "winrate": {"value": 72.55, "color": "#a00dbc"},
            "dmg": {"value": 110659, "color": "#d042f3"},
            "frags": {"value": 1.11, "color": "#44b300"},
            "planes": {"value": 6.78, "color": "#d042f3"},
            "pr": {"value": 2138, "color": "#d042f3"},
            "roman": "X",
        },
        "11": {
            "battles": 0,
            "winrate": {"value": 0, "color": "#fe0e00"},
            "dmg": {"value": 0, "color": "#fe0e00"},
            "frags": {"value": 0, "color": "#fe0e00"},
            "planes": {"value": 0, "color": "#fe0e00"},
            "pr": {"value": 0, "color": "#fe0e00"},
            "roman": "★",
        },
    },
    "type": {
        "dd": {
            "battles": 450,
            "winrate": {"value": 77.11, "color": "#a00dbc"},
            "dmg": {"value": 62407, "color": "#d042f3"},
            "frags": {"value": 1.86, "color": "#d042f3"},
            "planes": {"value": 3.7, "color": "#44b300"},
            "pr": {"value": 3021, "color": "#a00dbc"},
        },
        "bb": {
            "battles": 140,
            "winrate": {"value": 77.14, "color": "#a00dbc"},
            "dmg": {"value": 79201, "color": "#d042f3"},
            "frags": {"value": 1.31, "color": "#02c9b3"},
            "planes": {"value": 6.17, "color": "#d042f3"},
            "pr": {"value": 1888, "color": "#02c9b3"},
        },
        "ca": {
            "battles": 582,
            "winrate": {"value": 72.68, "color": "#a00dbc"},
            "dmg": {"value": 81598, "color": "#d042f3"},
            "frags": {"value": 1.26, "color": "#02c9b3"},
            "planes": {"value": 5.92, "color": "#02c9b3"},
            "pr": {"value": 2293, "color": "#d042f3"},
        },
        "cv": {
            "battles": 288,
            "winrate": {"value": 67.71, "color": "#a00dbc"},
            "dmg": {"value": 90209, "color": "#d042f3"},
            "frags": {"value": 1.2, "color": "#02c9b3"},
            "planes": {"value": 5.22, "color": "#02c9b3"},
            "pr": {"value": 2166, "color": "#d042f3"},
        },
    },
    "clan": {"name": "[PANTS]", "color": "#cda4ff"},
    "user": {"uid": 2025455227, "nickname": "B2U"},
}
ship_rank_data = {
    "players": [
        {
            "rank": "1",
            "clan": "[BANSS]",
            "id": "Seyuki",
            "battles": "40",
            "pr": {"color": "#A00DC5", "value": "3138"},
            "winrate": {"color": "#A00DC5", "value": "82.5"},
            "frags": {"color": "#D042F3", "value": "1.8"},
            "dmg": {"color": "#D042F3", "value": "94513"},
            "planes": {"color": "#D042F3", "value": "15.97"},
        },
        {
            "rank": "2",
            "clan": "[GS]",
            "id": "niseredo",
            "battles": "41",
            "pr": {"color": "#A00DC5", "value": "2969"},
            "winrate": {"color": "#D042F3", "value": "60.98"},
            "frags": {"color": "#02C9B3", "value": "1.34"},
            "dmg": {"color": "#D042F3", "value": "105318"},
            "planes": {"color": "#02C9B3", "value": "4.17"},
        },
        {
            "rank": "3",
            "clan": "[BANSS]",
            "id": "Blanquillo",
            "battles": "119",
            "pr": {"color": "#A00DC5", "value": "2860"},
            "winrate": {"color": "#A00DC5", "value": "74.79"},
            "frags": {"color": "#D042F3", "value": "1.49"},
            "dmg": {"color": "#D042F3", "value": "88500"},
            "planes": {"color": "#D042F3", "value": "12"},
        },
        {
            "rank": "4",
            "clan": "[PANTS]",
            "id": "Kancollce_Ushiolove",
            "battles": "73",
            "pr": {"color": "#A00DC5", "value": "2754"},
            "winrate": {"color": "#A00DC5", "value": "71.23"},
            "frags": {"color": "#02C9B3", "value": "1.37"},
            "dmg": {"color": "#D042F3", "value": "87875"},
            "planes": {"color": "#D042F3", "value": "7.16"},
        },
        {
            "rank": "5",
            "clan": "[NEU]",
            "id": "DowlinAryea",
            "battles": "52",
            "pr": {"color": "#A00DC5", "value": "2739"},
            "winrate": {"color": "#A00DC5", "value": "78.85"},
            "frags": {"color": "#02C9B3", "value": "1.38"},
            "dmg": {"color": "#D042F3", "value": "84331"},
            "planes": {"color": "#D042F3", "value": "7.71"},
        },
        {
            "rank": "6",
            "clan": "LaGalissonniere",
            "id": "",
            "battles": "61",
            "pr": {"color": "#A00DC5", "value": "2702"},
            "winrate": {"color": "#A00DC5", "value": "65.57"},
            "frags": {"color": "#D042F3", "value": "1.69"},
            "dmg": {"color": "#D042F3", "value": "82703"},
            "planes": {"color": "#D042F3", "value": "6.28"},
        },
        {
            "rank": "7",
            "clan": "[PANTS]",
            "id": "B2U",
            "battles": "46",
            "pr": {"color": "#A00DC5", "value": "2568"},
            "winrate": {"color": "#A00DC5", "value": "76.09"},
            "frags": {"color": "#02C9B3", "value": "1.43"},
            "dmg": {"color": "#D042F3", "value": "78852"},
            "planes": {"color": "#D042F3", "value": "10.5"},
        },
        {
            "rank": "8",
            "clan": "[GNK48]",
            "id": "Noob__DD",
            "battles": "40",
            "pr": {"color": "#A00DC5", "value": "2501"},
            "winrate": {"color": "#A00DC5", "value": "70"},
            "frags": {"color": "#02C9B3", "value": "1.27"},
            "dmg": {"color": "#D042F3", "value": "84247"},
            "planes": {"color": "#D042F3", "value": "8.22"},
        },
        {
            "rank": "9",
            "clan": "[VTB]",
            "id": "liejinyinhe",
            "battles": "73",
            "pr": {"color": "#A00DC5", "value": "2498"},
            "winrate": {"color": "#D042F3", "value": "60.27"},
            "frags": {"color": "#02C9B3", "value": "1.3"},
            "dmg": {"color": "#D042F3", "value": "83447"},
            "planes": {"color": "#D042F3", "value": "9.21"},
        },
        {
            "rank": "10",
            "clan": "[AYAYA]",
            "id": "L007_Killer",
            "battles": "40",
            "pr": {"color": "#D042F3", "value": "2436"},
            "winrate": {"color": "#A00DC5", "value": "80"},
            "frags": {"color": "#D042F3", "value": "1.45"},
            "dmg": {"color": "#D042F3", "value": "72700"},
            "planes": {"color": "#D042F3", "value": "9.97"},
        },
        {
            "rank": "11",
            "clan": "[PANTS]",
            "id": "CandyIona",
            "battles": "50",
            "pr": {"color": "#D042F3", "value": "2371"},
            "winrate": {"color": "#A00DC5", "value": "78"},
            "frags": {"color": "#D042F3", "value": "1.6"},
            "dmg": {"color": "#02C9B3", "value": "67541"},
            "planes": {"color": "#D042F3", "value": "9.4"},
        },
        {
            "rank": "12",
            "clan": "[CATS]",
            "id": "Iridescent_Remix",
            "battles": "205",
            "pr": {"color": "#D042F3", "value": "2361"},
            "winrate": {"color": "#A00DC5", "value": "73.17"},
            "frags": {"color": "#02C9B3", "value": "1.3"},
            "dmg": {"color": "#D042F3", "value": "72869"},
            "planes": {"color": "#D042F3", "value": "8.9"},
        },
        {
            "rank": "13",
            "clan": "[MALD]",
            "id": "Ninym_Ralei",
            "battles": "163",
            "pr": {"color": "#D042F3", "value": "2328"},
            "winrate": {"color": "#A00DC5", "value": "80.98"},
            "frags": {"color": "#02C9B3", "value": "1.28"},
            "dmg": {"color": "#02C9B3", "value": "69130"},
            "planes": {"color": "#D042F3", "value": "8.99"},
        },
        {
            "rank": "14",
            "clan": "[BANSS]",
            "id": "LeiaPrPrPr",
            "battles": "42",
            "pr": {"color": "#D042F3", "value": "2322"},
            "winrate": {"color": "#A00DC5", "value": "69.05"},
            "frags": {"color": "#44B300", "value": "1.02"},
            "dmg": {"color": "#D042F3", "value": "79251"},
            "planes": {"color": "#D042F3", "value": "8.67"},
        },
        {
            "rank": "15",
            "clan": "[RDT]",
            "id": "voidhata",
            "battles": "50",
            "pr": {"color": "#D042F3", "value": "2279"},
            "winrate": {"color": "#A00DC5", "value": "74"},
            "frags": {"color": "#44B300", "value": "1.04"},
            "dmg": {"color": "#D042F3", "value": "74451"},
            "planes": {"color": "#02C9B3", "value": "4.72"},
        },
    ],
    "ship": {
        "name": "Groningen",
        "tier": "IX",
        "img": "https://glossary-wows-global.gcdn.co/icons//vehicle/small/PHSD509_ddeb7e5ec30944adf68ccc663a790f2b9b6de4e9cea0878da188cce906df712f.png",
    },
    "region": "ASIA",
}

clan_data = {
    "region": "asia",
    "mbr_count": "50",
    "active_mbr_count": "40",
    "pr": {"color": "#02C9B3", "value": "1826"},
    "winrate": {"color": "#D042F3", "value": "61.01"},
    "dmg": {"color": "#D042F3", "value": "69248"},
    "strength": {
        "ca": "97",
        "cv": "64",
        "dd": "93",
        "bb": "87",
        "total": "85",
        "cw": "94",
    },
    "clan": {
        "renamed": [
            {
                "name": "COMET",
                "fullname": "Sui-Chan is Cute Today Too!",
                "date": "April 02, 2020",
            }
        ],
        "name": "[REPOI]",
        "color": "#cda4ff",
        "uid": 2000017400,
        "fullname": "POISoda\u00ae Donkey Waxing Service",
        "description": "Welcome to our waxing station. Here at REPOI, we have the best waxers available, ready to wax your donkey with sublime service. Our mission is to provide the best waxing service to the donkeys of the world\n\nBecause our members hail from a myriad of nations, this is an English-speaking clan\n\n--------------------------------------------------------------\n\nRecruitment: Referral by clan members. Although do feel free to throw in an application if you like!\n\nDiscord : https://discord.gg/UR8cGPv",
        "seasons": [
            {
                "season": 15,
                "battles": 194,
                "winrate": {"value": 59.28, "color": "#02c9b3"},
                "league": 0,
                "color": "#cda4ff",
                "division": "I",
                "division_rating": 75,
                "max": {
                    "league": 0,
                    "color": "#cda4ff",
                    "division": 1,
                    "division_rating": 97,
                },
            },
            {
                "season": 14,
                "battles": 156,
                "winrate": {"value": 62.18, "color": "#d042f3"},
                "league": 0,
                "color": "#cda4ff",
                "division": "I",
                "division_rating": 53,
                "max": {
                    "league": 0,
                    "color": "#cda4ff",
                    "division": 1,
                    "division_rating": 53,
                },
            },
            {
                "season": 13,
                "battles": 271,
                "winrate": {"value": 55.72, "color": "#318000"},
                "league": 0,
                "color": "#cda4ff",
                "division": "I",
                "division_rating": 41,
                "max": {
                    "league": 0,
                    "color": "#cda4ff",
                    "division": 1,
                    "division_rating": 52,
                },
            },
            {
                "season": 12,
                "battles": 110,
                "winrate": {"value": 76.36, "color": "#a00dbc"},
                "league": 0,
                "color": "#cda4ff",
                "division": "I",
                "division_rating": 141,
                "max": {
                    "league": 0,
                    "color": "#cda4ff",
                    "division": 1,
                    "division_rating": 141,
                },
            },
        ],
    },
}

output = Renderer().render_path("./renderer_template/clan.mu", clan_data)
im = screenshot(output)
im.show()
