name: cd
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build Binary
        id: build
        run: |
          cargo build --release
      
      - name: rsync
        uses: contention/rsync-deployments@v2.0.0
        with:
          flags:
          excludes:
          user: ${{ secrets.DEPLOY_USERNAME }}
          host: ${{ secrets.DEPLOY_HOST }}
          localpath: target/release/isac-rs
          remotepath: ${{ secrets.DEPLOY_PATH }}
          deploy_key: ${{ secrets.DEPLOY_SSH_KEY }}
        

      # - name: Deploy to VPS
      #   if: ${{ steps.build.outcome == 'success' }}
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.DEPLOY_HOST }}
      #     username: ${{ secrets.DEPLOY_USERNAME }}
      #     key: ${{ secrets.DEPLOY_SSH_KEY }}
      #     script: |
      #       rsync target/release/isac-rs ${{ secrets.DEPLOY_PATH }}
